version: '3.4'
services:
  mongo:
    image: mongo:3.6.3
    # UNCOMMENT TO ENABLE STORAGE OF DB IN HOST
    # volumes:
    #   - mongo:/data/db
    expose:
      - "27017"

  app:
    build:
      context: .
      dockerfile: python-dev
    command: ["python", "-m", "uaebackend.app"]
    ports:
      - "80:5000"
    volumes:
      - './logs:/app/logs'
    links:
      - mongo
