version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: python-dev
    command: ["python", "-m", "uaebackend.app"]
    ports:
      - "80:5000"
    volumes:
      - './logs:/app/logs'

